#server:
#  port:8086
spring:
datasource:
  driverClassName:org.h2.Driver
  url:jdbc:h2:mem:dbtest
  username:ang
  password:P@ssw0rd
jpa:
  database-platform:org.hibernate.dialect.H2Dialect
h2:
  console.enabled:true

server:
  port: 8085




